- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: print files and folders
    ansible.builtin.command: ls -l
    register: OUTPUT

  - name: print output
    ansible.builtin.debug:
      msg: "{{OUTPUT}}"
  
  - name: redirect the output
    ansible.builtin.shell: ls -l > /tmp/output.txt

  - name: redirect the output
    ansible.builtin.command: ps -ef | grep ssh

  - name: print env variables
    ansible.builtin.shell: env
    register: environment

  - name: print output
    ansible.builtin.debug:
      msg: "{{ environment }}"