- name: create ec2 and r53
  hosts: local
  connection: local
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      vpc_subnet_id: "subnet-09863c54177764565"
      instance_type: t3.micro
      security_group: sg-09a300a3729062c5a
      image_id: "ami-09c813fb71547fc4f"
    loop:
    - {name: 'mysql'}
    - {name: 'backend'}
    - {name: 'frontend'}
    register: ec2_instances

  - name: print the information
    ansible.builtin.debug:
      msg: ec2_instances