- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    instances:
    - {name: 'mysql'}
    - {name: 'backend'}
    - {name: 'frontend'}
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      vpc_subnet_id: "subnet-09863c54177764565"
      instance_type: t3.micro
      security_group: sg-09a300a3729062c5a
      image_id: "ami-09c813fb71547fc4f"
    loop: "{{instances}}"
    register: ec2_instances

  - name: print the information
    ansible.builtin.debug:
      msg: "{{ec2_instances.results[0].item.name}}, {{ec2_instances.results[0].instances[0].private_ip_address}}"

  - name: update R53 records
    amazon.aws.route53:
      state: present
      zone: daws81s.online
      record: "{{ item.item.name }}.daws81s.online"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_instances.results }}"

  - name: update R53 record for frontend
    amazon.aws.route53:
      state: present
      zone: daws81s.online
      record: "daws81s.online"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item.name == "frontend"